version: '3.5'

services:

  coworkee-cmd:
    container_name: 'container_cmd'
    image: rockmagicnet/sencha-cmd:latest
    volumes:
      - ./client:/var/www
    working_dir: /var/www
    ports:
      - 1841:1841

  coworkee-node-cli:
    container_name: 'coworkee-node-cli'
    image: node:6.9.2-alpine
    volumes:
      - ./server:/var/www
    working_dir: /var/www
    ports:
      - 3000:3000